{{- if eq (include "bambuddy.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bambuddy.secretName" . }}
  labels:
    {{- include "bambuddy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (eq .Values.database.type "postgresql") (not .Values.database.externalDatabase.existingSecret) }}
  database-url: {{ include "bambuddy.postgresUrl" . | quote }}
  {{- end }}
  {{- if and .Values.config.homeAssistant.token (not .Values.config.homeAssistant.existingSecret) }}
  ha-token: {{ .Values.config.homeAssistant.token | quote }}
  {{- end }}
  {{- if and .Values.config.mfa.encryptionKey (not .Values.config.mfa.existingSecret) }}
  mfa-encryption-key: {{ .Values.config.mfa.encryptionKey | quote }}
  {{- end }}
{{- end }}
